[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --workspace=apps/api --include-workspace-root"]

[phases.build]
cmds = ["npm run build --workspace=apps/api"]

[start]
cmd = "node apps/api/dist/main"
